[package]
name = "update_workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
cargo_toml = "0.10.1"
serde = "1.0.130"
toml = "0.5.8"
